#(@)ot-recorder.default
#
# Specify global configuration options for the OwnTracks Recorder
# and its associated utilities to override compiled-in defaults.
# Lines beginning with # are comments
# *** In libconfig versions < 1.4 a trailing semicolon is mandatory

# -----------------------------------------------------
# Storage directory
#
OTR_STORAGEDIR="/mnt/owntracks/recorder"
OTR_HOST="localhost"
OTR_HTTPHOST="[::]"
OTR_HTTPPORT=8083
# OTR_HTTPLOGDIR=""

# -----------------------------------------------------
# API key for reverse-geo lookups
#
# OTR_GEOKEY=""
# -----------------------------------------------------
# Reverse geo precision
#
# OTR_PRECISION=7
# -----------------------------------------------------
# Reverse geo cache expiration time in seconds
# Purge geo gcache entries after these seconds; default 0, disable with 0
# OTR_CLEAN_AGE=0
# -----------------------------------------------------
# Browser API key for Google maps
# OTR_BROWSERAPIKEY=""
# -----------------------------------------------------
# List of topics for MQTT to subscribe to, blank separated in a string
OTR_TOPICS="owntracks/#"
# -----------------------------------------------------
# Optional LUA script which will be loaded with the Recorder
# OTR_LUASCRIPT="/path/to/script.lua"
# -----------------------------------------------------
# HTTP prefix for this recorder for accessing Tour views
# OTR_HTTPPREFIX="https://owntracks.example/owntracks"