# traefik config to prevent it from trampling the internal nginx server
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        expose:
          default: true
        exposedPort: 8080
        
      websecure:
        expose
          default: true
        exposedPort: 8443
        tls:
          certResolver: leresolver
          domains:
            - main: "kokuzo"
              sans:
                - "kokuzo.tailc38f.ts.net"
